// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Klj_M9VQuJCqr1jOvLy2aCiu-K0tvdQ',
    appId: '1:36656908864:web:0d74f0a8621193fdb82da5',
    messagingSenderId: '36656908864',
    projectId: 'airy-adapter-387710',
    authDomain: 'airy-adapter-387710.firebaseapp.com',
    storageBucket: 'airy-adapter-387710.appspot.com',
    measurementId: 'G-N1WK791GHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbevHxFVwGE8-vHWPEJDEWuw-5iHROKBI',
    appId: '1:36656908864:android:3b448ae234a071d3b82da5',
    messagingSenderId: '36656908864',
    projectId: 'airy-adapter-387710',
    storageBucket: 'airy-adapter-387710.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmO9do_KP2pLY8eqWs0BIXdSX044RPMQg',
    appId: '1:36656908864:ios:c7075922f0d3c233b82da5',
    messagingSenderId: '36656908864',
    projectId: 'airy-adapter-387710',
    storageBucket: 'airy-adapter-387710.appspot.com',
    iosBundleId: 'com.example.puppyPalace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmO9do_KP2pLY8eqWs0BIXdSX044RPMQg',
    appId: '1:36656908864:ios:308e5ab431432a4eb82da5',
    messagingSenderId: '36656908864',
    projectId: 'airy-adapter-387710',
    storageBucket: 'airy-adapter-387710.appspot.com',
    iosBundleId: 'com.example.puppyPalace.RunnerTests',
  );
}
